<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.0.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'MDG Newsletter Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'aragusin@mdgglobal.com',
		'to' => 'aragusin@mdgglobal.com'
	),
	'fields' => array(
		'custom_U22396' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'First Name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'First Name\' is required.'
			)
		),
		'Email' => array(
			'order' => 5,
			'type' => 'email',
			'label' => 'Email',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Email\' is required.',
				'format' => 'Field \'Email\' has an invalid email.'
			)
		),
		'custom_U22371' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Company',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Company\' is required.'
			)
		),
		'custom_U22375' => array(
			'order' => 11,
			'type' => 'string',
			'label' => 'Message',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U22404' => array(
			'order' => 4,
			'type' => 'checkbox',
			'label' => '3D Emblems',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U22400' => array(
			'order' => 8,
			'type' => 'checkbox',
			'label' => 'Fusion',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U22418' => array(
			'order' => 10,
			'type' => 'checkbox',
			'label' => 'Crystal Doming',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U22387' => array(
			'order' => 12,
			'type' => 'checkbox',
			'label' => 'Vinyl Graphics',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U22391' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'Last Name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Last Name\' is required.'
			)
		),
		'custom_U22408' => array(
			'order' => 13,
			'type' => 'checkbox',
			'label' => 'Presentations',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U22422' => array(
			'order' => 3,
			'type' => 'checkbox',
			'label' => 'Shows/Events',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U22414' => array(
			'order' => 7,
			'type' => 'checkbox',
			'label' => 'New Products',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U22379' => array(
			'order' => 9,
			'type' => 'checkbox',
			'label' => 'Dealer Promotions',
			'required' => false,
			'errors' => array(
			)
		)
	)
);

process_form($form);
?>
